<?php

/**
 * @file
 * Functions to support theming in the gnuschichten theme.
 */

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function gnuschichten_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $suggestions[] = 'page__' . $node->bundle();
    $suggestions[] = 'page__node_' . $node->bundle();
  }
}
